export const sidebarlinks = [
    {
        label:"Home",
        icon:"/home-in.svg",
        activeicon:"/home.svg",
        path:"/"
    },
    {
        label:"Designs",
        icon:"/design-in.svg",
        activeicon:"/design.svg",
        path:"/Design"
    },
    {
        label:"Message",
        icon:"/message-in.svg",
        activeicon:"/message.svg",
        path:"/messages"
    },
    {
        label:"Connections",
        icon:"/network-in.svg",
        activeicon:"/network.svg",
        path:"/connections"
    },
    {
        label:"Notifications",
        icon:"/notifi-in.svg",
        activeicon:"/notification-act.svg",
        path:"#"
    },
    {
        label:"Marketplace",
        icon:"/market-in.svg",
        activeicon:"/market.svg",
        path:"#"
    }
,
    {
        label:"Settings",
        icon:"/settings-in.svg",
        activeicon:"/settings.svg",
        path:"#"
    }
]