import Event from "@/component/Event";
import Post from "@/component/Post";
import Sidebar from "@/component/Sidebar";
import Mainlayout from "@/layouts/Mainlayout";
import Head from "next/head";
import Image from "next/image";
import React from "react";

function index() {
  return (
    <Mainlayout>
      <div className="h-[100vh] w-[100vw] flex justify-center items-center">
        <Head>
          <title>DevsUi</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="h-[90%] w-[90%] bg-slate-700">
          <section className="h-[100%] w-[65%] flex flex-col justify-start items-center border-2 border-red-100">
            <div className="h-[105px] w-[100%] bg-[#121212] flex flex-col items-center justify-evenly rounded-lg">
              <div className="h-[40px] w-[90%] flex items-center justify-between border-[2px] border-[#2d2b2b] rounded-3xl">
                <input
                  className="text-sm text-white font-normal h-[100%] w-[70%] rounded-3xl pl-4 box-border  bg-[#121212] focus:outline-none"
                  type="text"
                  placeholder="Search here..."
                />
                <Image
                  className="mr-1"
                  width={32}
                  height={32}
                  src={"/searchh.svg"}
                  alt=""
                />
              </div>
              <div className="h-[40px] w-[85%] flex items-center justify-between">
                <Event
                  image="/gallery.svg"
                  text="Home"
                  height={22}
                  width={22}
                />
                <Event image="/shop.svg" text="Work" height={20} width={20} />
                <Event image="/Event.svg" text="Event" height={17} width={17} />
              </div>
            </div>
            <Post />
          </section>
        </div>
      </div>
    </Mainlayout>
  );
}

export default index;
